---
- name: Download filebeat's rpm"
  get_url:
    url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ fb_version }}-x86_64.rpm"
    dest: "/tmp/filebeat-{{ fb_version }}-x86_64.rpm"
  register: download_fb
  until: download_fb is succeeded